#!/usr/bin/env bash

function abort() {
    echo -n $1
    exit 1
}

echo -e "\n== SANITY CHECK: GIT STATUS ==\n"
git status
echo -e "\nIs everything committed?  (Ctrl-C if not!) "
read

CURR_BRANCH_OR_TAG=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)
rm -rf tmp tutorial/book
mdbook build tutorial || abort "Couldn't build the tutorial mdbook"
git switch gh-pages || abort "Couldn't switch to the gh-pages branch"
if ! git pull origin gh-pages ; then
    git switch $CURR_BRANCH_OR_TAG
    abort "Couldn't pull the remote gh-pages branch. Please switch to gh-pages and pull manually."
fi
rm -rf FontAwesome css fonts
mv -f tutorial/book/* .
git add -A
git commit -m "update tutorial"
git push origin HEAD
git switch $CURR_BRANCH_OR_TAG
