name: Publish Tutorial
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: install stable Rust toolchain
        id: install_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          # Don't use a 'components:' entry--we don't need them with beta/nightly, plus nightly often doesn't have them
          override: true

      - name: install mdbook
        run: cargo install mdbook

      - name: build tutorial 🔧
        run: mdbook build tutorial

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: tutorial/book # The folder the action should deploy.
